### PR TITLE
Add vehicle colors jpg file

### PR DESCRIPTION
**Pull request by mrgharabaghi**
The `placeholder.com` is currently unavailable.
Check the link below:
https://via.placeholder.com/15/0d1116/0d1116.png

### CODE REVIEW

**Comment by C0kkie** [comment]
Upload the images please here https://github.com/altmp/altv-docs-assets

**Comment by mrgharabaghi** [comment]
Done

**Comment by C0kkie** [comment]
You should use ~/altv-docs-assets/altv-docs-gta/images/vehicle/colors/

as path for the images

**Comment by mrgharabaghi** [comment]
Done

**Comment by C0kkie** [comment]
Thanks

**Pull request merged**
